### ISSUE TITLE
Showing questionmark "?" instead of Number

### ISSUE THREAD

**Issue by Shorepion** [Krxwallo/SimpleFPS#1]
Minecraft version: 1.16.3
Forge version: 34.1.42

Any idea how to fix it?

![2020-11-23_19 40 58](https://user-images.githubusercontent.com/24994890/100002283-a4673800-2dc4-11eb-956d-5f64de6870e2.png)

**Comment by Krxwallo** [comment]
This is probably a Bug, I will look into it soon...

**Comment by Krxwallo** [comment]
Can you post your debug.log? It works fine for me with mc 1.16.3.

**Comment by Krxwallo** [comment]
This has probably to do with an other mod you're using...

**Comment by Krxwallo** [comment]
See other issue for newest forge ver
