### ISSUE TITLE
? fps

### ISSUE THREAD

**Issue by Zygus42** [Krxwallo/SimpleFPS#2]
After installing the mod, all I'm getting is a "? FPS" in the upper-left corner - no number.

![2021-01-25_12 54 26](https://user-images.githubusercontent.com/20757445/105663198-9a6ccd00-5f0c-11eb-8dc5-32f99efc1427.png)

simple_fps-1.16.X-1.2.0
forge 1.16.5

**Comment by Krxwallo** [comment]
post your debug.log please

**Comment by Zygus42** [comment]
Sorry - been testing a modpack, so I have 1000s of zipped logs - no clue which one this was.

**Comment by Krxwallo** [comment]
latest.log?

**Comment by Zygus42** [comment]
[2021-01-25-10.log.gz](https://github.com/Krxwallo/SimpleFPS/files/5901842/2021-01-25-10.log.gz)

Found this after looking at more than 20 logs - hope it helps.

**Comment by Krxwallo** [comment]
I can't find anything in that log...

**Comment by Krxwallo** [comment]
Ima try it out on 1.16.5 without mods in a bit

**Comment by JillSwift** [comment]
Having the same issue. Here's a debug.log from my last session. Hope it illuminates:
[debug.zip](https://github.com/Krxwallo/SimpleFPS/files/6007893/debug.zip)

**Comment by Krxwallo** [comment]
I think this mod is conflicting with some other mod you are playing with. Could you try it out without other mods or send me the modpack for testing?

**Comment by Krxwallo** [comment]
> Sorry - been testing a modpack, so I have 1000s of zipped logs - no clue which one this was.

Could you send me the modpack aswell?

**Comment by Zygus42** [comment]
It's changed a lot since I tried using this mod - not sure it would help at this point.  Also the mod folder is 456 MB.

**Comment by Krxwallo** [comment]
Ima try it out myself maybe it is because of the new forge version

**Comment by JillSwift** [comment]
Hi!
Just tried it out with SimpleFPS the only mod. Same issue.
MC 1.16.4
Forge 35.1.37

[debug.log](https://github.com/Krxwallo/SimpleFPS/files/6009588/debug.log)

**Comment by Krxwallo** [comment]
ok thx I will fix it soon

**Comment by Krxwallo** [comment]
BTW why are you using the latest not recommended forge release?

> Forge 35.1.37

**Comment by JillSwift** [comment]
I am using a couple of mods that require it.

**Comment by Krxwallo** [comment]
I tried it out with 1.16.5 36.0.46 it worked perfectly fine...

**Comment by Krxwallo** [comment]
1.16.4 35.1.37 works fine aswell
